# This section defines the dataset file path
file_paths:
  beacons: 'data/calibration/beacons/beacons_calibration.txt'
  gt: 'data/calibration/gt/gt_calibration.txt'

# This section defines the parameters for each anchor
# Distance in centimeters
# Do not change the anchors ID names
anchors:
  - id: 6501
    coordinates: [0, 300, 230] # Anchor 6501 coordinates
    ref_coordinates: [120, 300, 110] # Reference coordinate for path-loss model - in centimeters
  - id: 6502
    coordinates: [600, 0, 230]
    ref_coordinates: [600, 120, 110]
  - id: 6503
    coordinates: [1200, 300, 230]
    ref_coordinates: [1080, 300, 110]
  - id: 6504
    coordinates: [600, 600, 230]
    ref_coordinates: [600, 480, 110]

# This section defines configuration settings for calibration scenarios
calibration:
  begin_X: 120 # Starting position of the calibration points on the X-axis, in centimeters
  end_X: 1080 # Final position of the calibration points on the X-axis, in centimeters
  begin_Y: 120 # Starting position of the calibration points on the Y-axis, in centimeters
  end_Y: 480 # Final position of the calibration points on the Y-axis, in centimeters
  Z_score: 2 # Z-score threshold to remove RSSI outliers

# This section configures additional resources
additional:
  x_grid_limit: [-2.00, 8.00] # X-axis grid limit for plots, in meters
  y_grid_limit: [-2.00, 14.00] # Y-axis grid limit for plots, in meters
  plot_first_path: True # Change this value if you want to plot the estimated path generated by the algorithms only during the first run.
  plot_all_paths: False # Change this value if you want to plot the estimated path generated by the algorithms in every run.
  plot_first_RSSI: True # Change this value if you want to plot the RSSI curve in the calibration code for only the 6501 anchor.
  plot_all_RSSI: False # Change this value if you want to plot the RSSI curve in the calibration code for all anchors.
  plot_error_bargraph: True # Change this value if you want to plot the bar graph with the average distance errors.
  plot_CDF: True # Change this value if you want to plot the CDF of the average distance error.
  polarization: 2ndP # The polarization used – If you want to see the RSSI behavior with a different polarization, change it to '1stP'.
