# This section defines the dataset file path
file_paths:
  case_1:
    run1:
      beacons: 'data/mobility/beacons/use-case 1/beacons_mobility_use-case1_run1.txt'
      gt: 'data/mobility/gt/use-case 1/gt_mobility_use-case1_run1.txt'
    run2:
      beacons: 'data/mobility/beacons/use-case 1/beacons_mobility_use-case1_run2.txt'
      gt: 'data/mobility/gt/use-case 1/gt_mobility_use-case1_run2.txt'
    run3:
      beacons: 'data/mobility/beacons/use-case 1/beacons_mobility_use-case1_run3.txt'
      gt: 'data/mobility/gt/use-case 1/gt_mobility_use-case1_run3.txt'
    run4:
      beacons: 'data/mobility/beacons/use-case 1/beacons_mobility_use-case1_run4.txt'
      gt: 'data/mobility/gt/use-case 1/gt_mobility_use-case1_run4.txt'

  case_2:
    run1:
      beacons: 'data/mobility/beacons/use-case 2/beacons_mobility_use-case2_run1.txt'
      gt: 'data/mobility/gt/use-case 2/gt_mobility_use-case2_run1.txt'
    run2:
      beacons: 'data/mobility/beacons/use-case 2/beacons_mobility_use-case2_run2.txt'
      gt: 'data/mobility/gt/use-case 2/gt_mobility_use-case2_run2.txt'
    run3:
      beacons: 'data/mobility/beacons/use-case 2/beacons_mobility_use-case2_run3.txt'
      gt: 'data/mobility/gt/use-case 2/gt_mobility_use-case2_run3.txt'
    run4:
      beacons: 'data/mobility/beacons/use-case 2/beacons_mobility_use-case2_run4.txt'
      gt: 'data/mobility/gt/use-case 2/gt_mobility_use-case2_run4.txt'

  case_3:
    run1:
      beacons: 'data/mobility/beacons/use-case 3/beacons_mobility_use-case3_run1.txt'
      gt: 'data/mobility/gt/use-case 3/gt_mobility_use-case3_run1.txt'
    run2:
      beacons: 'data/mobility/beacons/use-case 3/beacons_mobility_use-case3_run2.txt'
      gt: 'data/mobility/gt/use-case 3/gt_mobility_use-case3_run2.txt'
    run3:
      beacons: 'data/mobility/beacons/use-case 3/beacons_mobility_use-case3_run3.txt'
      gt: 'data/mobility/gt/use-case 3/gt_mobility_use-case3_run3.txt'
    run4:
      beacons: 'data/mobility/beacons/use-case 3/beacons_mobility_use-case3_run4.txt'
      gt: 'data/mobility/gt/use-case 3/gt_mobility_use-case3_run4.txt'

# This section defines the parameters for each anchor
# Do not change the anchors ID names
anchors:
  - id: 6501
    alpha: 1.329 # Path-loss coefficent
    coordinates: [0, 300, 230] # Anchor 6501 coordinates - in centimeters
    ref_coordinates: [120, 300, 110] # Reference coordinate for path-loss model
  - id: 6502
    alpha: 1.852
    coordinates: [600, 0, 230]
    ref_coordinates: [600, 120, 110]
  - id: 6503
    alpha: 1.420
    coordinates: [1200, 300, 230]
    ref_coordinates: [1080, 300, 110]
  - id: 6504
    alpha: 2.012
    coordinates: [600, 600, 230]
    ref_coordinates: [600, 480, 110]

# This section defines Kalman filter parameters
kalman_filter:
  delta_T: 0.2 #sampling time
  A: [[1, 0.2, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.2], [0, 0, 0, 1]] # State Transition Matrix (if the sampling time changes, modify this matrix)
  C: [[1, 0, 0, 0], [0, 0, 1, 0]] #Observation Matrix
  Q: [[8, 0, 0, 0], [0, 8, 0, 0], [0, 0, 8, 0], [0, 0, 0, 8]] # Initial Noise Covariance Matrix of the Process
  R_MLT: [[250, 0], [0, 250]] # MLT Measurement Noise
  R_AoA_RSSI: [[250, 0], [0, 250]] # AoA+RSSI Measurement Noise
  R_AoA_only: [[25, 0], [0, 25]] # AoA-only Measurement Noise
  P: [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]] #Initial Error Covariance

# This section configures additional resources
additional:
  plot_first_path: True # Change this value if you want to plot the estimated path generated by the algorithms only during the first run.
  plot_all_paths: False # Change this value if you want to plot the estimated path generated by the algorithms in every run.
  plot_error_bargraph: True # Change this value if you want to plot the bar graph with the average distance errors.
  plot_CDF: True # Change this value if you want to plot the CDF of the average distance error.
  case_1:
    initial_position: [240, 480] # in centimeters
  case_2:
    initial_position: [960, 120] # in centimeters
  case_3:
    initial_position: [240, 480] # in centimeters
