# This section defines the dataset file path
file_paths:
  beacons: 'data/calibration/beacons/beacons_calibration.txt'
  gt: 'data/calibration/gt/gt_calibration.txt'

# This section defines the parameters for each anchor
# Distance in centimeters
# Do not change the anchors ID names
anchors:
  - id: 6501
    coordinates: [0, 300, 230] # Anchor 6501 coordinates
    ref_coordinates: [120, 300, 110] # Reference coordinate for path-loss model - in centimeters
  - id: 6502
    coordinates: [600, 0, 230]
    ref_coordinates: [600, 120, 110]
  - id: 6503
    coordinates: [1200, 300, 230]
    ref_coordinates: [1080, 300, 110]
  - id: 6504
    coordinates: [600, 600, 230]
    ref_coordinates: [600, 480, 110]

# This section defines configuration settings for path-loss coefficient estimation
rssi:
  polarization_column: '2ndP' # 1stP or 2ndP
  Z_score: 2 # Z-score threshold to remove RSSI outliers

# This section configures additional resources
plot:
  fig_size: [12, 8] # [width, height] in inches
